fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

album:
    resource: "@AlbumBundle/Resources/config/routing.yml"
    prefix:   /album

#album_i18n:
#    resource: i18n
#    type: album_i18n