<?php

namespace AlbumBundle\Repository;

/**
 * AlbumCoverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumCoverRepository extends \Doctrine\ORM\EntityRepository
{
}
