<?php

namespace AlbumBundle\Repository;

/**
 * AlbumFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumFontRepository extends \Doctrine\ORM\EntityRepository
{
}
